"""
This converts the masks in the search directory generated by MLLMs that is colorful jpeg to P-mode png.
"""

import os
import glob
from tqdm import tqdm
from pixel_arena.image_processing import mask_raw_to_pmode
from typing import List, Literal
import logging

SEARCH_DIR = "./test-shuffle"
DATASET = "celeb"

logger = logging.getLogger("convert_masks")


def batch_process_images(
    search_dir: str,
    dataset: Literal["celeb", "coco"],
    label_colors: List[List[int]] | None,
    attempts: int,
    force: bool = False,
):
    # Search for files matching the pattern in ./test
    # Pattern: *.mask.[0, 1, 2].raw.{jpg, png}
    # We can use glob with a character set for [0-2]
    search_pattern_png = os.path.join(search_dir, f"*.mask.[0-{attempts - 1}].raw.png")
    search_pattern_jpg = os.path.join(search_dir, f"*.mask.[0-{attempts - 1}].raw.jpg")
    files = glob.glob(search_pattern_png) + glob.glob(search_pattern_jpg)

    print(f"Found {len(files)} files to process.")

    skip_count = 0
    process_count = 0

    for file_path in tqdm(files):
        try:
            # Construct output path
            # Replace .raw.{jpg, png} with .pred.png
            output_path = file_path.replace(".raw.jpg", ".pred.png").replace(
                ".raw.png", ".pred.png"
            )

            if os.path.exists(output_path) and not force:
                logger.info(f"Output path {output_path} already exists, skipping.")
                skip_count += 1
                continue

            # Process
            result_image = mask_raw_to_pmode(file_path, dataset, label_colors)
            # Save
            result_image.save(output_path)
            process_count += 1
        except Exception as e:
            print(f"Error processing {file_path}: {e}")

    print(f"Skipped {skip_count} files, processed {process_count} files.")


if __name__ == "__main__":
    batch_process_images(
        SEARCH_DIR, dataset=DATASET, label_colors=None, attempts=5, force=False
    )
