[project]
name = "cv-is-dead"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asynciolimiter>=1.2.0",
    "google-genai>=1.52.0",
    "matplotlib>=3.10.7",
    "openai>=2.8.1",
    "pillow>=12.0.0",
    "torch>=2.9.1",
    "torchmetrics>=1.8.2",
    "torchvision>=0.24.1",
    "tqdm>=4.67.1",
]

[dependency-groups]
dev = ["ipykernel>=7.1.0", "poethepoet>=0.37.0", "ruff>=0.14.5"]

[tool.ruff]
extend-exclude = ["frontend/**"]

[tool.poe.tasks]
format-python = "ruff format"
check-python = "ruff check"
format = ["format-python", "format-frontend"]

[tool.poe.tasks.format-frontend]
cmd = "bun run format"
cwd = "frontend"

[tool.poe.tasks.check-frontend]
cmd = "bun run lint"
cwd = "frontend"

[tool.poe.tasks.setup-frontend]
cmd = "bun install"
cwd = "frontend"

[tool.poe.tasks.run-frontend]
cmd = "bun dev"
cwd = "frontend"
