"""
This upscales the reference masks from 512 to 1024 resolution since the masks generated by Gemini are 1024.
"""

import os
import glob
from PIL import Image
from tqdm import tqdm


def main():
    # Directories
    input_dir = "./eval-set/celeb/masks-512"
    output_dir = "./eval-set/celeb/masks-1024"
    target_size = (1024, 1024)

    # Create output directory if it doesn't exist
    os.makedirs(output_dir, exist_ok=True)

    # Find all png files in input directory
    files = glob.glob(os.path.join(input_dir, "*.png"))

    print(f"Found {len(files)} mask files to upscale.")

    for file_path in tqdm(files):
        try:
            filename = os.path.basename(file_path)
            output_path = os.path.join(output_dir, filename)

            # Open image
            # PIL should automatically handle P mode if the file is P mode
            img = Image.open(file_path)

            # Verify mode
            original_mode = img.mode

            # Resize with Nearest Neighbor to preserve integer labels
            # If it's P mode, resizing usually converts to RGB unless we are careful,
            # but resize on P mode image with NEAREST should preserve it in recent PIL versions
            # or we might need to ensure palette is kept.

            upscaled = img.resize(target_size, resample=Image.NEAREST)

            # If the original was P, ensure the upscaled is also P and has the same palette
            if original_mode == "P" and upscaled.mode != "P":
                # This case shouldn't happen with NEAREST usually, but if it does:
                upscaled = upscaled.convert("P")
                upscaled.putpalette(img.getpalette())
            elif original_mode == "P":
                # Ensure palette is preserved exactly
                upscaled.putpalette(img.getpalette())

            # Save
            upscaled.save(output_path)

        except Exception as e:
            print(f"Error processing {file_path}: {e}")


if __name__ == "__main__":
    main()
